### ISSUE TITLE
CssImportPreProcessor mishandle //** comments

### ISSUE THREAD

**Issue by SomMeri** [alexo/wro4j#187] opened 2014-07-08 06:31 UTC
If the input less file contains `//** blah` style comment, the `removeImportsFromComments` method of `CssImportInspector` removes everything between it and closest `*/`. 

Simple example less:
````
//** deleting the comment removes the problem
@body-bg:               #fff;

/**
 * deleting the comment removes the problem
 */
@import  "variables.less";
@mainColor: blue;
 
h1,h2,h3,h4,h5,h6,h7,h8 {
	color: @mainColor;
	font-weight: normal;
}
````

is transformed into syntactically incorrect:
````
/
@import  "variables.less";
@mainColor: blue;
 
h1,h2,h3,h4,h5,h6,h7,h8 {
	color: @mainColor;
	font-weight: normal;
}
````

Context: attempts to import variables.less file from bootstrap and compile the result using wro4j leads to compile error in less4j https://github.com/SomMeri/less4j/issues/208 .

**Comment by M3lkior** [comment] 2015-03-17 10:37
I tried to update your code @alexo  but the project is voluminous and i'm affraid to do regression with pull request :/

**Comment by mrcage** [comment] 2015-09-02 15:20
Any update on this issue? Currently, compiling the current Bootstrap v3.3.5 fails with wro4j due to this...

**Comment by alexo** [comment] 2015-09-03 06:26
@mrcage this issue was migrated to the new project home page: https://github.com/wro4j/wro4j/issues/976 
I will try to fix, but it would help a lot if there is anyone willing to help.

**Comment by mrcage** [comment] 2015-09-03 11:16
Thanks. I do not know the wro4j code, but I could help in testing the bugfix in the next release candidate.

**Comment by alexo** [comment] 2015-09-05 15:14
This issue is fixed and will be released in next version. The fix can be found at the new  location of the project: https://github.com/wro4j/wro4j/issues/976

**Closed by alexo** 2015-09-05 15:14 UTC

**Comment by mrcage** [comment] 2015-09-10 11:49
Thanks a lot for fixing this.
